default_language_version:
  python: python3.7
default_stages: [commit, push]
repos:
- repo: https://github.com/PyCQA/flake8
  rev: 3.7.8
  hooks:
  - id: flake8
    args:
      - "--max-line-length=100"
- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
  - id: isort
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.760
  hooks:
  - id: mypy
