default_language_version:
  python: python3.7
default_stages: [commit, push]
repos:
- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.770
  hooks:
  - id: mypy
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.1.4
  hooks:
  - id: isort